import { Montserrat } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const montSerratFont = Montserrat({
  weight: ["100", "200", "400", "700"],
  subsets: ["cyrillic", "latin"],
});

export const metadata = {
  title: "My Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${montSerratFont.style} antialiased`}>
        <Navbar />
        <main>{children}</main>
      </body>
    </html>
  );
}
